# Generated by Django 2.2.24 on 2023-04-14 10:52

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner_name,
            pure_phone=flat.owner_pure_phone,
            phonenumber=flat.owners_phonenumber
            )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230414_1345'),
    ]

    operations = [
        migrations.RunPython(fill_owners),
    ]
