# Generated by Django 2.2.24 on 2023-04-14 11:28

from django.db import migrations


def fill_owner_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get(
            name=flat.owner_name,
            pure_phone=flat.owner_pure_phone
            )
        owner.flats.add(flat)
        

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230414_1352'),
    ]

    operations = [
        migrations.RunPython(fill_owner_flats),
    ]
